#test spring application

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Junit stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running Junit Test'
        steps:
          - script: echo 'Running spring demo unit test case'
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true